#!/bin/bash

probname=$1 ;
minrun=$2;
maxrun=$3;
mingen=$4;
maxgen=$5;

_usage()
{
	# ./burstpfall zdt1 1 10 1 200
	printf '%s\n' "Usage: ./burstpfall [problem name] [minrun] [maxrun] [mingen] [maxgen]";
	exit 0;
}

if [[ -z $probname ]] || [[ -z $minrun ]] || [[ -z $maxrun ]] || [[ -z $mingen ]] || [[ -z $maxgen ]]; then
	echo "error: some of the parameters are missing, hence exiting ...";
	_usage ;
fi

nohup ./sh/burstpfn $minrun $maxrun $mingen $maxgen \
	experiments/nsga2r/$probname/all_pop- \
	experiments/nsga2r/$probname/ >& /dev/null &

nohup ./sh/burstpfn $minrun $maxrun $mingen $maxgen \
	experiments/onsga2r/$probname/all_pop- \
	experiments/onsga2r/$probname/ >& /dev/null & 
	
nohup ./sh/burstpfn $minrun $maxrun $mingen $maxgen \
    	experiments/onsga2r/$probname/all_source- \
    	experiments/onsga2r/$probname/ >& /dev/null &

nohup ./sh/burstpfn $minrun $maxrun $mingen $maxgen \
    	experiments/onsga2r/$probname/all_opposite- \
    	experiments/onsga2r/$probname/ >& /dev/null &

nohup ./sh/burstpfn $minrun $maxrun $mingen $maxgen \
	experiments/onsga2r/$probname/all_survived- \
	experiments/onsga2r/$probname/ >& /dev/null &
