#!/bin/bash
# runs genpfsnaps over the results from multiple runs

startrun=$1
endrun=$2
mingen=$3;
maxgen=$4;
srcfileprefix=$5;
destdirparent=$6;
destdirprefix="$destdirparent"pfsnaps-run

_usage()
{
	# example: ./burstpfn 1 10 1 100 experiments/nsga2r/zdt1/all_pop-
	#				experiments/nsga2r/zdt1/
	printf '%s\n\t\t  %s\n' "Usage: ./burstpfn [startrun] [endrun] [mingen] [maxgen]" "[srcfile-prefix] [destdir-parent]";
	exit 0;
}

if [[ -z $startrun ]] || [[ -z $endrun ]]; then
	echo "error: some of the parameters are missing, hence exiting ...";
	_usage ;
fi

for (( i=$startrun; i<=$endrun; i++ ))
do
	srcfile="$srcfileprefix$i.out" ;
	destdir="$destdirprefix-$i" ;
	if [ ! -d "$destdir" ]; then
		mkdir $destdir ;
	fi
	./sh/burstpf "$mingen" "$maxgen" "$srcfile" "$destdir" ;
done
