#!/bin/bash
# this scripts generates pdf plot from the files generated
# by gensnaps script

args=("$@");
len=${#args[@]};
nobj=${args[0]};
mingen=${args[1]};
maxgen=${args[2]};
outdir=${args[3]};
prefixargs=("${args[@]:4:$len}");

_usage()
{
	# ./genplots 1 100 outdir /some/where/file1 /some/where/file2 some/where/file3 ...
	printf '%s\n\t\t  %s\n' "Usage: ./genplots [nobj] [mingen] [maxgen] [outputdir]" "[N input-file prefix argumets]";
	exit 0;
}

if [[ $len -lt 5 ]]; then
	echo "error: some of the parameters are missing, hence exiting ...";
	_usage ;
fi

if [ ! -d "$outdir" ]; then
	mkdir "$outdir" ;
fi

filelist=();
for (( j=$mingen; j<=$maxgen; j++ ))
do
	# echo "gen = $j" ;
	for (( i=0; i<"${#prefixargs[@]}"; i++ ))
	do
		# echo "file: ${prefixargs[i]}"
		prefix="${prefixargs[i]}";
		if [[ $prefix == *"/"* ]]; then
			title=`echo $prefix | awk -F"/" '{print $NF}' | awk -F"." '{print $1}'`
		else
			title=`echo $prefix | awk -F"." '{print $1}'`
		fi
		# echo "i = $i" ;
		# echo "prefix: $prefix$j.out" ;
		# echo "title: $title$j.out" ;
		if [[ -f "$prefix$j.out" ]]; then
			feval=$(cat "$prefix$j.out" | head -n 1 | awk -F"= " '{print $3}');
			if [[ $i -eq 0 ]]; then
				# cat "$prefix$j.out" | head -n 1
				# echo "feval: $feval" ;
				# fevallist+=("$feval");
				filelist+=("\"$prefix$j.out\" title \"$title$j\"");
			else
				filelist+=(", \"$prefix$j.out\" title \"$title$j\"");
			fi
		fi
	done
	echo "feval: $feval";
	echo "making plots with ${filelist[@]}";
	echo "" ;
	# findex=$((j - 1)) ;
	# note: for tex, use: set term pdf enhanced color
	if [[ $nobj -eq 2 ]]; then
		gnuplot <<- EOF
			set term push
			set term pdf color
			set output "${outdir}/pf-gen-${j}.pdf"
			set title "gen = ${j}, feval = $feval"
			plot ${filelist[@]}
			set term pop
		EOF
	elif [[ $nobj -gt 2 ]]; then
		gnuplot <<- EOF
			set term push
			set term pdf color
			set output "${outdir}/pf-gen-${j}.pdf"
			set title "gen = ${j}, feval = $feval"
			splot ${filelist[@]}
			set term pop
		EOF
	fi
	filelist=();
	# fevallist=();
done
