#!/bin/bash
# compute hypervolume for a single run

len=$# ;
mingen=$1 ;
maxgen=$2 ;
infileprefix=$3 ;
outdir=$4 ;
hvparamfile=$5

_usage()
{
	# ./calchv 1 100 experiments/nsga2r/zdt1/pfsnaps-run-1/all_pop-1-gen- 
	#		 experiments/nsga2r/zdt1/
	#		 whv/zdt1-param.txt
	printf '%s\n' "Usage: ./calchv [mingen] [maxgen] [in-file-prefix] [outdir] [hv-param-file]";
	exit 0;
}

if [[ $len -lt 5 ]]; then
	echo "error: some of the parameters are missing, hence exiting ...";
	_usage ;
fi

hvdir="hv";
hvdirpath="$outdir""$hvdir";
suffix=`echo $infileprefix | awk -F"/" '{print $NF}' ;`
run=`echo $suffix | awk -F"-" '{print $2}'` ;

# echo mingen: $mingen ;
# echo maxgen: $maxgen ;
# echo infileprefix: $infileprefix ;
# echo outdir: $outdir ;
# echo hvdirpath: $hvdirpath ;
# echo suffix: $suffix ;
# echo run: $run ;

if [ ! -d "$hvdirpath" ]; then
	mkdir "$hvdirpath" ;
fi

uid=$RANDOM ;
for (( i=$mingen; i<=$maxgen; i++ ))
do
	rawpffile="$infileprefix$i".out ;
	cat $rawpffile | tail -n +2 | awk -F" " '{print $1" "$2}' > /tmp/temp-"$uid".out ;
	hvval=`whv/hyp_ind $hvparamfile /tmp/temp-"$uid".out /tmp/temp-"$uid".out /dev/stdout` ;
	if [ "$i" -eq $mingen ]; then
		printf "%d\t%e\n" "$i" "$hvval" > $hvdirpath/hv-run-$run.out ;
	else
		printf "%d\t%e\n" "$i" "$hvval" >> $hvdirpath/hv-run-$run.out ;
	fi
done
rm -f /tmp/temp-"$uid".out ;
